import { ResolverVantagePoint } from '../types/dns.js';

export const GLOBAL_RESOLVER_VANTAGES: ResolverVantagePoint[] = [
  {
    id: 'cf-primary',
    provider: 'Cloudflare',
    resolverIp: '1.1.1.1',
    locationLabel: 'Global / Anycast Resolver (Cloudflare Edge)',
    country: 'Global Anycast',
    continent: 'North America',
    latitude: 38.9072,
    longitude: -77.0369,
    tier: 'privacy',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://cloudflare-dns.com/dns-query'
  },
  {
    id: 'cf-secondary',
    provider: 'Cloudflare',
    resolverIp: '1.0.0.1',
    locationLabel: 'Global / Anycast Resolver (Cloudflare Edge)',
    country: 'Global Anycast',
    continent: 'Europe',
    latitude: 51.5074,
    longitude: -0.1278,
    tier: 'privacy',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://cloudflare-dns.com/dns-query'
  },
  {
    id: 'google-primary',
    provider: 'Google Public DNS',
    resolverIp: '8.8.8.8',
    locationLabel: 'Global / Anycast Resolver (Google Anycast)',
    country: 'Global Anycast',
    continent: 'North America',
    latitude: 37.7749,
    longitude: -122.4194,
    tier: 'public',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://dns.google/resolve'
  },
  {
    id: 'google-secondary',
    provider: 'Google Public DNS',
    resolverIp: '8.8.4.4',
    locationLabel: 'Global / Anycast Resolver (Google Anycast)',
    country: 'Global Anycast',
    continent: 'Asia',
    latitude: 35.6762,
    longitude: 139.6503,
    tier: 'public',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://dns.google/resolve'
  },
  {
    id: 'quad9-primary',
    provider: 'Quad9',
    resolverIp: '9.9.9.9',
    locationLabel: 'Global / Anycast Resolver (Quad9 Secure)',
    country: 'Global Anycast',
    continent: 'Europe',
    latitude: 47.3769,
    longitude: 8.5417,
    tier: 'security',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://dns.quad9.net/dns-query'
  },
  {
    id: 'quad9-secondary',
    provider: 'Quad9',
    resolverIp: '149.112.112.112',
    locationLabel: 'Global / Anycast Resolver (Quad9 Secondary)',
    country: 'Global Anycast',
    continent: 'North America',
    latitude: 34.0522,
    longitude: -118.2437,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'opendns-primary',
    provider: 'Cisco OpenDNS',
    resolverIp: '208.67.222.222',
    locationLabel: 'Global / Anycast Resolver (Cisco OpenDNS)',
    country: 'Global Anycast',
    continent: 'North America',
    latitude: 40.7128,
    longitude: -74.006,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'opendns-secondary',
    provider: 'Cisco OpenDNS',
    resolverIp: '208.67.220.220',
    locationLabel: 'Global / Anycast Resolver (Cisco OpenDNS)',
    country: 'Global Anycast',
    continent: 'Europe',
    latitude: 48.8566,
    longitude: 2.3522,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'adguard-primary',
    provider: 'AdGuard DNS',
    resolverIp: '94.140.14.14',
    locationLabel: 'Global / Anycast Resolver (AdGuard Anycast)',
    country: 'Global Anycast',
    continent: 'Europe',
    latitude: 50.1109,
    longitude: 8.6821,
    tier: 'privacy',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://dns.adguard.com/dns-query'
  },
  {
    id: 'adguard-secondary',
    provider: 'AdGuard DNS',
    resolverIp: '94.140.15.15',
    locationLabel: 'Global / Anycast Resolver (AdGuard Anycast)',
    country: 'Global Anycast',
    continent: 'Asia',
    latitude: 1.3521,
    longitude: 103.8198,
    tier: 'privacy',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'cleanbrowsing-primary',
    provider: 'CleanBrowsing',
    resolverIp: '185.228.168.9',
    locationLabel: 'Global / Anycast Resolver (CleanBrowsing)',
    country: 'Global Anycast',
    continent: 'South America',
    latitude: -23.5505,
    longitude: -46.6333,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'cf-security',
    provider: 'Cloudflare Security',
    resolverIp: '1.1.1.2',
    locationLabel: 'Global / Anycast Resolver (Cloudflare Malware Block)',
    country: 'Global Anycast',
    continent: 'Oceania',
    latitude: -33.8688,
    longitude: 151.2093,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'controld-primary',
    provider: 'Control D',
    resolverIp: '76.76.2.0',
    locationLabel: 'Global / Anycast Resolver (Control D Anycast)',
    country: 'Global Anycast',
    continent: 'North America',
    latitude: 43.6532,
    longitude: -79.3832,
    tier: 'security',
    networkType: 'anycast',
    transport: 'UDP'
  },
  {
    id: 'alidns-primary',
    provider: 'Alibaba AliDNS',
    resolverIp: '223.5.5.5',
    locationLabel: 'Global / Anycast Resolver (Alibaba AliDNS)',
    country: 'Global Anycast',
    continent: 'Asia',
    latitude: 31.2304,
    longitude: 121.4737,
    tier: 'public',
    networkType: 'anycast',
    transport: 'DOH',
    dohEndpoint: 'https://dns.alidns.com/resolve'
  }
];
